Repository LikeLionTeam/BootHouse, pull requests merged in 2024-09, with the labels that each got.

#95 feat: Course 크롤링
  view/build.gradle
  view/src/main/java/likelion/eight/domain/course/controller/CourseRestController.java
  view/src/main/java/likelion/eight/domain/course/model/CrawledCourses.java
  view/src/main/java/likelion/eight/domain/course/service/CourseCrawlingService.java
Labels: Type:Feature, For: Business

#96 Feat/#user chat
  db/src/main/java/likelion/eight/chatlist/ChatListEntity.java
  db/src/main/java/likelion/eight/chatlist/ifs/ChatListJpaRepository.java
  db/src/main/java/likelion/eight/chatroom/ChatroomEntity.java
  db/src/main/java/likelion/eight/chatroom/ifs/ChatroomJpaRepository.java
  db/src/main/java/likelion/eight/message/ifs/MessageJpaRepository.java
  db/src/main/java/likelion/eight/user/ifs/UserJpaRepository.java
  view/build.gradle
  view/src/main/java/likelion/eight/ViewApplication.java
  view/src/main/java/likelion/eight/common/config/redis/RedisConfig.java
  view/src/main/java/likelion/eight/common/config/web/WebSocketConfig.java
  view/src/main/java/likelion/eight/domain/chat/controller/ChatController.java
  view/src/main/java/likelion/eight/domain/chat/controller/ChatRestController.java
  view/src/main/java/likelion/eight/domain/chat/controller/WebSocketChatController.java
  view/src/main/java/likelion/eight/domain/chat/infrastructure/ChatRoomRedisRepository.java
  view/src/main/java/likelion/eight/domain/chat/model/ChatMessage.java
  view/src/main/java/likelion/eight/domain/chat/model/ChatRoom.java
  view/src/main/java/likelion/eight/domain/chat/service/ChatService.java
  view/src/main/java/likelion/eight/domain/user/infra/UserRepositoryImpl.java
  view/src/main/java/likelion/eight/domain/user/service/UserService.java
  view/src/main/java/likelion/eight/domain/user/service/port/UserRepository.java
  view/src/main/resources/static/js/chat/chatList/index.js
  view/src/main/resources/static/js/chat/chatList/messageUpdates.js
  view/src/main/resources/static/js/chat/chatList/modal.js
  view/src/main/resources/static/js/chat/chatList/newChatButton.js
  view/src/main/resources/static/js/chat/chatList/searchInput.js
  view/src/main/resources/static/js/chat/chatList/userList.js
  view/src/main/resources/static/js/chat/chatRoom/chatActions.js
  view/src/main/resources/static/js/chat/chatRoom/chatOptions.js
  view/src/main/resources/static/js/chat/chatRoom/index.js
  view/src/main/resources/static/js/chat/chatRoom/messageHandling.js
  view/src/main/resources/static/js/chat/chatRoom/websocketConnection.js
  view/src/main/resources/static/js/chat/chatroom.js
  view/src/main/resources/templates/chat/chatroom.html
  view/src/main/resources/templates/chat/messages.html
  view/src/main/resources/templates/index.html
Labels: Type:Feature, For: Business

#98 배포를 위한 수정 및 dockerfile 작성
  Dockerfile
  view/build.gradle
  view/src/main/java/likelion/eight/domain/course/controller/CourseRestController.java
  view/src/main/java/likelion/eight/domain/course/service/CourseCrawlingService.java
  view/src/main/java/likelion/eight/domain/likeCourse/controller/LikeCourseController.java
  view/src/main/java/likelion/eight/domain/likeReview/controller/LikeReviewController.java
  view/src/main/java/likelion/eight/domain/notice/controller/NoticeController.java
  view/src/main/resources/templates/index.html
Labels: Type: Refactor, Type:Feature

#99 Refactor/common
  db/src/main/java/likelion/eight/likeCourse/LikeCourseJpaRepository.java
  db/src/main/java/likelion/eight/log/LogEntity.java
  view/build.gradle
  view/src/main/java/likelion/eight/ViewApplication.java
  view/src/main/java/likelion/eight/common/controller/HomeController.java
  view/src/main/java/likelion/eight/common/controller/NavbarController.java
  view/src/main/java/likelion/eight/domain/course/controller/CourseController.java
  view/src/main/java/likelion/eight/domain/course/service/CourseService.java
  view/src/main/java/likelion/eight/domain/likecourse/controller/LikeCourseController.java
  view/src/main/java/likelion/eight/domain/likecourse/model/LikeCourseRes.java
  view/src/main/java/likelion/eight/domain/likecourse/service/LikeCourseService.java
  view/src/main/java/likelion/eight/domain/likereview/controller/LikeReviewController.java
  view/src/main/java/likelion/eight/domain/likereview/model/LikeReviewRes.java
  view/src/main/java/likelion/eight/domain/likereview/service/LikeReviewService.java
  view/src/main/java/likelion/eight/domain/token/service/TokenCookieService.java
  view/src/main/java/likelion/eight/domain/token/service/TokenService.java
  view/src/main/java/likelion/eight/domain/user/controller/MyPageController.java
  view/src/main/java/likelion/eight/domain/user/service/UserService.java
  view/src/main/java/likelion/eight/domain/userauth/service/S3Service.java
  view/src/main/java/likelion/eight/domain/userauth/service/S3ServiceImpl.java
  view/src/main/java/likelion/eight/domain/userauth/service/UserAuthS3Service.java
  view/src/main/java/likelion/eight/domain/userauth/service/UserAuthService.java
  view/src/main/java/likelion/eight/domain/usercourse/converter/UserCourseConverter.java
  view/src/main/java/likelion/eight/domain/usercourse/infra/UserCourseRepositoryImpl.java
  view/src/main/java/likelion/eight/domain/usercourse/model/UserCourse.java
  view/src/main/java/likelion/eight/domain/usercourse/service/UserCourseService.java
  view/src/main/java/likelion/eight/domain/usercourse/service/port/UserCourseRepository.java
  view/src/main/java/likelion/eight/interceptor/AuthorizationInterceptor.java
Labels: Type: Refactor, For: Common
